### ISSUE TITLE
在已存在迷你小窗时无法通过手势挂起第二个迷你小窗

### ISSUE THREAD

**Issue by QingXuer** [YifePlayte/MaxFreeForm#1]
最小化小窗只能有一个
能否把这个限制解除
在挂第二个的时候就会因为已经有一个小窗而无法挂起第二个小窗https://user-images.githubusercontent.com/97309254/182730144-c0769399-3764-4623-b3ae-176d21da59ef.mp4

系统MIUI 13.0.17稳定版
机型redmi k50

**Comment by xzrr-li** [comment]
目前好像得开发版内测才支持放置在侧边栏这个功能

**Comment by YifePlayte** [comment]
此bug已知，且不打算修复。MIUI的迷你小窗并没有多迷你小窗的逻辑，所以即使解开此限制也会引发更多bug。请使用在后台界面长按应用卡片后点击小窗按钮触发多小窗的方式替代直接挂起迷你小窗。
